### ISSUE TITLE
FASA | GroundRadar Error with FAOR

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#110]
@SkyyStorm just got this error logging on with the FASA Sector File (with all the latest development updates).

Could you take a look?

![image](https://user-images.githubusercontent.com/88507206/175783397-0bae16e4-0dc6-4e12-9122-2d22a8696181.png)

**Comment by SkyyStorm** [comment]
On it.

**Comment by SkyyStorm** [comment]
Fixed, notation was wrong, NONE of the stands were working!

**Comment by vCaptainMike** [comment]
> Fixed, notation was wrong, NONE of the stands were working!

Ouch. Glad we sorted it out.
