### ISSUE TITLE
FMMM FMCZ New Ground Layout

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#116]
3rd busiest airport in the FMMM Sector File, busiest Mayotte airport.

@defectivepotato All yours.

**To Do**

- [ ] KMZ Development
- [ ] KMZ Conversion to SCT Text File
- [ ] GNG Implementation of SCT Entries
- [ ] GNG Implementation of Text Labels
- [ ] GNG Implementation of Regions

**Ground Layout Development**

- [ ] 1 Runways
- [ ] 2 Taxiways
- [ ] 3 Aprons
- [ ] 4 Stopbars
- [ ] 5 Parking
- [ ] 6 Buildings
- [ ] 7 Labels
- [ ] 8 Stand Data

**Comment by vCaptainMike** [comment]
All yours @TimS-W

**Comment by TimS-W** [comment]
[FMCZ V1.zip](https://github.com/VATSSA-Operations/Sector-Files/files/9191127/FMCZ.V1.zip)
@vCaptainMike Please review

**Comment by vCaptainMike** [comment]
Reviewed and Implemented. Screenshot Below.

A few notes. Not used Taxiway Centerlines (reduce visual noise). Adjusted Apron vs Taxiway regions.


![image](https://user-images.githubusercontent.com/88507206/182037644-dbaf29cc-e1a4-4701-8c2e-85b7abd2ea32.png)
