### ISSUE TITLE
GOOO | GGOV Taxiway A Closed

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#139]
@SkyyStorm wanna take this one?

The idea is to do a GroundRadar Map with the blocked area (i'll do another for TopSky).

![image](https://user-images.githubusercontent.com/88507206/176419317-da6cdf0c-ace1-4743-9d8a-5269e7dc386f.png)

**Comment by SkyyStorm** [comment]
@vCaptainMike Sure, I did a similar thing with a taxiway that was closed at FAOR.
I'll get on to my tasks tomorrow, a bit swamped today and this evening.

**Comment by SkyyStorm** [comment]
@vCaptainMike So I've added the map, but I think the ground layout is not accurate, so its not lining up correctly, just as a side note.
![Screenshot 2022-07-03 161706](https://user-images.githubusercontent.com/20255491/177044018-2c7832ed-3da8-4524-ac32-5833bf8bd42a.png)

**Comment by vCaptainMike** [comment]
@SkyyStorm Clearly it is not. Will open a New Issue for Groundlayout Redesign.

![image](https://user-images.githubusercontent.com/88507206/177053076-7e899b75-ce68-4a1d-8678-37e083af9f29.png)
