### ISSUE TITLE
DBBB GroundRadar Stands

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#188]
I just need to review the GroundLayout on Euroscope first.

**Comment by vCaptainMike** [comment]
On hold until we get a new ground layout.

- #222

**Comment by SkyyStorm** [comment]
@vCaptainMike I dunno if a new ground layout exists yet, but something is not aligned here based on coordinates. 
![image](https://user-images.githubusercontent.com/20255491/179572439-41e79e4c-a5d0-436e-b55d-69e735de8241.png)

I will do a PR with the stands in the meantime.

**Comment by vCaptainMike** [comment]
@SkyyStorm , found the CALLSIGN:GROUP_DGAA_INT reference in the DBBB Stands (which naturally threw in an error, cause it's currently undefined).

Will you be adding the GROUP later?

**Comment by vCaptainMike** [comment]
There's a file called Airlines on Shared Resources - GroundRadar - Stands where I'm slowly adding airlines to groups that can be references on stand settings, if needed. Could be worth expanding.
