### ISSUE TITLE
FIMP GroundRadar Stand Data Review

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#229]
@SkyyStorm if you have some time, could you take a look at the FIMP GroundRadar Stand file?

Nothing wrong I see, but your expert eye could help identify any issue. Thank you.

**Comment by SkyyStorm** [comment]
> @SkyyStorm if you have some time, could you take a look at the FIMP GroundRadar Stand file?
> 
> Nothing wrong I see, but your expert eye could help identify any issue. Thank you.

Roger roger, will take a look tonight.
