### ISSUE TITLE
DNMM RWY 18L/36R Temp Closure

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#250]
A0281/22 - RWY 18L/36R CLSD. 08 JUL 00:00 2022 UNTIL 05 SEP 23:59 2022. CREATED: 05 JUL
19:24 2022

Implement

- [ ] GroundRadar
- [ ] TopSky

**Comment by vCaptainMike** [comment]
@SkyyStorm wanna take GroundRadar, I'll take TopSky?

**Comment by SkyyStorm** [comment]
@vCaptainMike Sure thing, I'll do this one and the other task Monday evening when I get a chance, if that's in time
