### ISSUE TITLE
VATSSA Global | Introduce Placeholder Position

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#63]
![image](https://user-images.githubusercontent.com/88507206/175021401-4a02553e-7863-419d-a4de-8d0868717c30.png)

**Comment by vCaptainMike** [comment]
Joshua's example.

![image](https://user-images.githubusercontent.com/88507206/175039909-328a4c97-9d52-4594-b350-f2173b90e2ee.png)

**Comment by defectivepotato** [comment]
![image](https://user-images.githubusercontent.com/99800587/175316335-0993d310-4e01-4138-a0f0-ddbbbb74304e.png)
My Example
