### ISSUE TITLE
FHSH New Ground Layout

### ISSUE THREAD

**Issue by vCaptainMike** [VATSSA-Operations/Sector-Files#79]
Mistery finally solved. Someone put the FHAW Ground Layout Code into FHSH.

Therefore, we don't have a FHSH Ground Layoyut.

**To Do**

- [x] KMZ Development
- [x] KMZ Conversion to SCT Text File
- [x] GNG Implementation of SCT Entries
- [x] GNG Implementation of Text Labels
- [x] GNG Implementation of Regions

**Ground Layout Development**

- [x] 1 Runways
- [x] 2 Taxiways
- [x] 3 Aprons
- [x] 4 Stopbars
- [x] 5 Parking
- [x] 6 Buildings
- [x] 7 Labels
- [x] 8 Stand Data

**Comment by defectivepotato** [comment]
[FHSH.zip](https://github.com/VATSSA-Operations/Sector-Files/files/8975688/FHSH.zip)

**Comment by vCaptainMike** [comment]
@defectivepotato , a couple of requests:

-     Organize the objects into folders (Runways, Taxiways, etc..)
-     Rename Objects that represent Parking Positions
-     Are you able to add Labels to this?
